services:
  wordpress:
    image: wordpress:latest
    ports:
      - 80:80
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=wordpress.cnvf8jqbx5pp.us-east-1.rds.amazonaws.com:3306
      - WORDPRESS_DB_USER="admin"
      - WORDPRESS_DB_PASSWORD="12345678"
      - WORDPRESS_DB_NAME="mysql"